#pragma once

#define ANSI_RESET "\e[0m"

#define ANSI_CLEAR_TERMINAL "\e[2J\e[1;1H"

#define ANSI_MOVE_CURSOR_LEFT_1 "\033[D"

#define ANSI_AIRCRAFT_CARRIER_COLOR ANSI_RED_FOREGROUND
#define ANSI_BATTLESHIP_COLOR       ANSI_CYAN_FOREGROUND
#define ANSI_CRUISER_COLOR          ANSI_GREEN_FOREGROUND
#define ANSI_SUBMARINE_COLOR        ANSI_DARK_YELLOW_FOREGROUND
#define ANSI_DESTROYER_COLOR        ANSI_MAGENTA_FOREGROUND

#define PRINT_AIRCRAFT_CARRIER_WITH_COLOR ANSI_AIRCRAFT_CARRIER_COLOR << '#' << ANSI_RESET
#define PRINT_BATTLESHIP_WITH_COLOR       ANSI_BATTLESHIP_COLOR       << '#' << ANSI_RESET
#define PRINT_CRUISER_WITH_COLOR          ANSI_CRUISER_COLOR          << '#' << ANSI_RESET
#define PRINT_SUBMARINE_WITH_COLOR        ANSI_SUBMARINE_COLOR        << '#' << ANSI_RESET
#define PRINT_DESTROYER_WITH_COLOR        ANSI_DESTROYER_COLOR        << '#' << ANSI_RESET

#define HIGHLIGHT_SELECTED_CELL_BACKGROUND_COLOR ANSI_BRIGHT_YELLOW_BACKGROUND

// https://gist.github.com/RabaDabaDoba/145049536f815903c79944599c6f952a
// https://gist.github.com/JBlond/2fea43a3049b38287e5e9cefc87b2124?permalink_comment_id=4481079#gistcomment-4481079

#define ANSI_BLACK_FOREGROUND   "\e[0;30m"
#define ANSI_RED_FOREGROUND     "\e[0;31m"
#define ANSI_GREEN_FOREGROUND   "\e[0;32m"
#define ANSI_YELLOW_FOREGROUND  "\e[0;33m"
#define ANSI_BLUE_FOREGROUND    "\e[0;34m"
#define ANSI_MAGENTA_FOREGROUND "\e[0;35m"
#define ANSI_CYAN_FOREGROUND    "\e[0;36m"
#define ANSI_WHITE_FOREGROUND   "\e[0;37m"

#define ANSI_BRIGHT_BLACK_FOREGROUND    "\e[0;90m"
#define ANSI_BRIGHT_RED_FOREGROUND      "\e[0;91m"
#define ANSI_BRIGHT_GREEN_FOREGROUND    "\e[0;92m"
#define ANSI_BRIGHT_YELLOW_FOREGROUND   "\e[0;93m"
#define ANSI_BRIGHT_BLUE_FOREGROUND     "\e[0;94m"
#define ANSI_BRIGHT_MAGENTA_FOREGROUND  "\e[0;95m"
#define ANSI_BRIGHT_CYAN_FOREGROUND     "\e[0;96m"
#define ANSI_BRIGHT_WHITE_FOREGROUND    "\e[0;97m"

#define ANSI_BLACK_BACKGROUND   "\e[40m"
#define ANSI_RED_BACKGROUND     "\e[41m"
#define ANSI_GREEN_BACKGROUND   "\e[42m"
#define ANSI_YELLOW_BACKGROUND  "\e[43m"
#define ANSI_BLUE_BACKGROUND    "\e[44m"
#define ANSI_MAGENTA_BACKGROUND "\e[45m"
#define ANSI_CYAN_BACKGROUND    "\e[46m"
#define ANSI_WHITE_BACKGROUND   "\e[47m"

#define ANSI_BRIGHT_BLACK_BACKGROUND    "\e[100m" // ???
#define ANSI_BRIGHT_RED_BACKGROUND      "\e[101m"
#define ANSI_BRIGHT_GREEN_BACKGROUND    "\e[102m"
#define ANSI_BRIGHT_YELLOW_BACKGROUND   "\e[103m"
#define ANSI_BRIGHT_BLUE_BACKGROUND     "\e[104m"
#define ANSI_BRIGHT_MAGENTA_BACKGROUND  "\e[105m"
#define ANSI_BRIGHT_CYAN_BACKGROUND     "\e[106m"
#define ANSI_BRIGHT_WHITE_BACKGROUND    "\e[107m"



#define ANSI_DARK_YELLOW_FOREGROUND "\033[38;5;94m"
#define ANSI_LIGHT_GREEN_FOREGROUND "\033[38;5;82m"
#define ANSI_LIGHT_GRAY_FOREGROUND "\033[38;5;7m"
#define ANSI_DARK_GRAY_FOREGROUND "\033[38;5;8m"